class Board:
    name = None  # Description as visible in skate shop
    texture = None  # Name of image file in Data/Textures/Boards
    is_extra = False  # Special or normally unused

    def __init__(self, name, texture, is_extra=False):
        self.name = name
        self.texture = texture
        self.is_extra = is_extra


class Boards:
    def get_grips(self):
        return self.all_grips.copy()

    def get_decks(self):
        return self.all_decks.copy()

    all_grips = [
        Board("Generic Cut", "GenericG01.png"),
        Board("Solid", "GenericG02.png"),
        Board("Razors edge", "GenericG03.png"),
        Board("Equal", "GenericG04.png"),
        Board("Slasher", "GenericG05.png"),
        Board("Square", "GenericG06.png"),
        Board("Ye Old School", "GenericG07.png"),
        Board("Striper", "GenericG08.png"),
        Board("Thrashed", "GenericG09.png"),
        Board("Colored Nuts", "GenericG010.png"),
        Board("Green Machine", "GenericG011.png"),
        Board("Blues", "GenericG012.png"),
        Board("Red Light", "GenericG013.png"),
        Board("Crack", "GenericG014.png"),
        Board("Eye dont know", "GenericG015.png"),
        Board("Hawk", "HawkG01.png"),
        Board("Bam", "margeraG01.png"),
        Board("Cab", "CaballeroG01.png"),
        Board("Glifberg", "GlifbergG01.png"),
        Board("Koston", "KostonG01.png"),
        Board("Mullen", "MullenG01.png"),
        Board("Muska", "MuskaG01.png"),
        Board("Steamer", "SteamerG01.png"),
        Board("Thomas", "thomasG01.png"),
        Board("You're a star", "DickG01.png"),
        Board("Ladies", "CarreraG01.png"),
        Board("Bat Grip", "DemonessG01.png"),
        Board("Slater", "SlaterG01.png", is_extra=True),
        Board("Scratch away", "WolverineG01.png"),
        Board("Broken", "OllieG01.png"),
        Board("Eyeball", "EyeballG01.png"),
        Board("DOOM Grip", "DoomG01.png", is_extra=True),
        Board("Birdhouse", "BirdhouseG01.png", is_extra=True),
        Board("CS NH Grip", "CS_NH_griptape.png", is_extra=True),
        Board("Dick", "DickG01 copy.png", is_extra=True),
        Board("Rowley", "RowleyG01.png", is_extra=True),
    ]

    all_decks = [
        Board("Birdman Crest", "HawkB01.png"),
        Board("Gold Edition Logo", "HawkB02.png"),
        Board("Team Seal 2001", "HawkB03.png"),
        Board("Hawk Collage", "HawkB04.png"),
        Board("Pterodactyl 2", "HawkB05.png"),
        Board("Pterodactyl skull", "HawkB06.png"),
        Board("3-D Logo", "HawkB07.png"),
        Board("Giant Pterodactyl Skull", "HawkB08.png"),
        Board("Pterodactyl 2001", "HawkB09.png"),
        Board("Tony Hawk Logo", "HawkB010.png"),
        Board("Chin Series - 1999", "caballeroB01.png"),
        Board("Cab Tank - 1993", "caballeroB02.png"),
        Board("Classic Dragon - 1999", "caballeroB03.png"),
        Board("Dragon - 2000", "caballeroB04.png"),
        Board("Face Series - 2000", "caballeroB05.png"),
        Board("Guitar Dragon - 1991", "caballeroB06.png"),
        Board("Harley the Dog - 1992", "caballeroB07.png"),
        Board("King Cab - 1993", "caballeroB08.png"),
        Board("Mini Dragon - 2000", "caballeroB09.png"),
        Board("Star Series - 2001", "caballeroB010.png"),
        Board("Citybot 8", "campbellB01.png"),
        Board("Sound Team Deck", "campbellB02.png"),
        Board("Viking", "campbellB03.png"),
        Board("Reemo Jr.", "campbellB04.png"),
        Board("Nude", "campbellB05.png"),
        Board("K.C. Star Deck", "campbellB06.png"),
        Board("Reemo Dwella ", "campbellB07.png"),
        Board("Ultra Violence 1.0", "campbellB08.png"),
        Board("Dragon", "campbellB09.png"),
        Board("Reemo! 2", "campbellB010.png"),
        Board("Glifberg 1", "glifbergB01.png"),
        Board("Glifberg 2", "glifbergB02.png"),
        Board("Glifberg 3", "glifbergB03.png"),
        Board("Glifberg 4", "glifbergB04.png"),
        Board("Glifberg 5", "glifbergB05.png"),
        Board("Glifberg 6", "glifbergB06.png"),
        Board("Glifberg 7", "glifbergB07.png"),
        Board("Glifberg 8", "glifbergB08.png"),
        Board("Glifberg 9", "glifbergB09.png"),
        Board("Glifberg 10", "glifbergB010.png"),
        Board("Classic Koston", "kostonB01.png"),
        Board("Mechanical", "kostonB02.png"),
        Board("Baseball", "kostonB03.png"),
        Board("Flag", "kostonB04.png"),
        Board("OG 2000", "kostonB05.png"),
        Board("Oldman", "kostonB06.png"),
        Board("Modern", "kostonB07.png"),
        Board("OG 2001", "kostonB08.png"),
        Board("Soccer", "kostonB09.png"),
        Board("Jumbo Girl", "kostonB010.png"),
        Board("Paradise Slammers", "lasekB01.png"),
        Board("Racecar", "lasekB02.png"),
        Board("3-D Logo", "lasekB03.png"),
        Board("Checkered Flag", "lasekB04.png"),
        Board("Racecar Logo", "lasekB05.png"),
        Board("Rooster", "lasekB06.png"),
        Board("Team Seal 2001", "lasekB07.png"),
        Board("Throttle", "lasekB08.png"),
        Board("Trophy Girls", "lasekB09.png"),
        Board("Nollie Flip", "lasekB010.png"),
        Board("Welcome", "margeraB01.png"),
        Board("Letterman", "margeraB02.png"),
        Board("Ivy League", "margeraB03.png"),
        Board("Bats", "margeraB04.png"),
        Board("Arbor", "margeraB05.png"),
        Board("Animalism", "margeraB06.png"),
        Board("Maninmal", "margeraB07.png"),
        Board("Trophy", "margeraB08.png"),
        Board("Instinct", "margeraB09.png"),
        Board("Script", "margeraB010.png"),
        Board("Rodney", "mullenB01.png"),
        Board("Duh!", "mullenB02.png"),
        Board("Panda Poo", "mullenB03.png"),
        Board("Boy Genius", "mullenB04.png"),
        Board("Old Man", "mullenB05.png"),
        Board("Panda Series", "mullenB06.png"),
        Board("Pigeon", "mullenB07.png"),
        Board("Quack", "mullenB08.png"),
        Board("Panda Mullen", "mullenB09.png"),
        Board("Kick Me", "mullenB010.png"),
        Board("Red Sun", "muskaB01.png"),
        Board("White Icon", "muskaB02.png"),
        Board("Orange Silhouette", "muskaB03.png"),
        Board("Blue Sun", "muskaB04.png"),
        Board("Red Team", "muskaB05.png"),
        Board("Green Sun", "muskaB06.png"),
        Board("Muska Icon", "muskaB07.png"),
        Board("Black Icon", "muskaB08.png"),
        Board("Muska Flight", "muskaB09.png"),
        Board("Red Silhouette", "muskaB010.png"),
        Board("Green Brand Logo", "reynoldsB01.png"),
        Board("White Baker Logo", "reynoldsB02.png"),
        Board("Baker Logo", "reynoldsB03.png"),
        Board("Red Brand Logo", "reynoldsB04.png"),
        Board("Black Cowboys", "reynoldsB05.png"),
        Board("Blue Brand Logo", "reynoldsB06.png"),
        Board("Yellow Baker Logo", "reynoldsB07.png"),
        Board("Monkey", "reynoldsB08.png"),
        Board("Green Baker Logo", "reynoldsB09.png"),
        Board("Rastas", "reynoldsB010.png"),
        Board("Rowley 1", "rowleyB01.png"),
        Board("Rowley 2", "rowleyB02.png"),
        Board("Rowley 3", "rowleyB03.png"),
        Board("Rowley 4", "rowleyB04.png"),
        Board("Rowley 5", "rowleyB05.png"),
        Board("Rowley 6", "rowleyB06.png"),
        Board("Rowley 7", "rowleyB07.png"),
        Board("Rowley 8", "rowleyB08.png"),
        Board("Rowley 9", "rowleyB09.png"),
        Board("Rowley 10", "rowleyB010.png"),
        Board("Etnies 1", "steamerB01.png"),
        Board("TSA 1", "steamerB02.png"),
        Board("Etnies 2", "steamerB03.png"),
        Board("TSA 2", "steamerB04.png"),
        Board("Etnies 3", "steamerB05.png"),
        Board("TSA 3", "steamerB06.png"),
        Board("Etnies 4", "steamerB07.png"),
        Board("TSA 4", "steamerB08.png"),
        Board("Etnies 5", "steamerB09.png"),
        Board("TSA 5", "steamerB010.png"),
        Board("Thomas Skeleton", "ThomasB01.png"),
        Board("Punk Green", "ThomasB02.png"),
        Board("American Punk", "ThomasB03.png"),
        Board("Red Bold", "ThomasB04.png"),
        Board("American Zero", "ThomasB05.png"),
        Board("Three Skull Black", "ThomasB06.png"),
        Board("Dying To Live", "ThomasB07.png"),
        Board("Zero or Die", "ThomasB08.png"),
        Board("Thomas Smith", "ThomasB09.png"),
        Board("Thomas Cross", "ThomasB010.png"),
        Board("Night Stick", "DickB01.png"),
        Board("CODE RED!", "DickB02.png"),
        Board("Dead or Alive", "DickB03.png"),
        Board("3 Donuts", "DickB04.png"),
        Board("Dick Ticket", "DickB05.png"),
        Board("I Still Got It", "DickB06.png"),
        Board("ATTACK!", "DickB07.png"),
        Board("Punishment", "DickB08.png"),
        Board("Mother?", "DickB09.png"),
        Board("Oops I did it Again", "DickB010.png"),
        Board("Carrera 1", "CarreraB01.png"),
        Board("Carrera 2", "CarreraB02.png"),
        Board("Carrera 3", "CarreraB03.png"),
        Board("Carrera 4", "CarreraB04.png"),
        Board("Carrera 5", "CarreraB05.png"),
        Board("Carrera 6", "CarreraB06.png"),
        Board("Carrera 7", "CarreraB07.png"),
        Board("Carrera 8", "CarreraB08.png"),
        Board("Carrera 9", "CarreraB09.png"),
        Board("Carrera 10", "CarreraB010.png"),
        Board("Fire Skull", "DemonessB01.png"),
        Board("Pitch", "DemonessB02.png"),
        Board("Bat Attack!", "DemonessB03.png"),
        Board("Widow Maker", "DemonessB04.png"),
        Board("Daddy-o", "DemonessB05.png"),
        Board("He Made Me Do it", "DemonessB06.png"),
        Board("Burn Baby Burn", "DemonessB07.png"),
        Board("Shrunken fun", "DemonessB08.png"),
        Board("10,000 Years", "DemonessB09.png"),
        Board("Rock N Roll", "DemonessB010.png"),
        Board("Wolverine 1", "wolverineB01.png"),
        Board("Wolverine 2", "wolverineB02.png"),
        Board("Wolverine 3", "wolverineB03.png"),
        Board("Wolverine 4", "wolverineB04.png"),
        Board("Wolverine 5", "wolverineB05.png"),
        Board("Wolverine 6", "wolverineB06.png"),
        Board("Wolverine 7", "wolverineB07.png"),
        Board("Wolverine 8", "wolverineB08.png"),
        Board("Wolverine 9", "wolverineB09.png"),
        Board("Wolverine 10", "wolverineB010.png"),
        Board("Maul 1", "MaulB01.png"),
        Board("Maul 2", "MaulB02.png"),
        Board("Maul 3", "MaulB03.png"),
        Board("Maul 4", "MaulB04.png"),
        Board("Maul 5", "MaulB05.png"),
        Board("Maul 6", "MaulB06.png"),
        Board("Maul 7", "MaulB07.png"),
        Board("Maul 8", "MaulB08.png"),
        Board("Maul 9", "MaulB09.png"),
        Board("Maul 10", "MaulB010.png"),
        Board("Slater 1", "SlaterB01.png"),
        Board("Splash", "SlaterB02.png"),
        Board("O2", "SlaterB03.png"),
        Board("Quick Red", "SlaterB04.png"),
        Board("Pro Green", "SlaterB05.png"),
        Board("Team Activision", "SlaterB06.png"),
        Board("Pro Blue", "SlaterB07.png"),
        Board("Quick Black", "SlaterB08.png"),
        Board("Slater 2", "SlaterB09.png"),
        Board("Pro Red", "SlaterB010.png"),
        Board("Skate For Food", "OllieB01.png"),
        Board("Triple X", "OllieB02.png"),
        Board("New Bed", "OllieB03.png"),
        Board("Grrr!", "OllieB04.png"),
        Board("I Eat Dirt", "OllieB05.png"),
        Board("Barrel Buddies", "OllieB06.png"),
        Board("Ollie Mug", "OllieB07.png"),
        Board("THE FLY", "OllieB08.png"),
        Board("Hobo Cart", "OllieB09.png"),
        Board("Thirst Money", "OllieB010.png"),
        Board("EyeBall 1", "EyeBallB01.png"),
        Board("Flamer Dark", "EyeBallB02.png"),
        Board("Classic", "EyeBallB03.png"),
        Board("Graf Head", "EyeBallB04.png"),
        Board("Thare Coming to get you", "EyeBallB05.png"),
        Board("Family Photo", "EyeBallB06.png"),
        Board("EyeBall 7", "EyeBallB07.png"),
        Board("EyeBall 8", "EyeBallB08.png"),
        Board("Flamer Light", "EyeBallB09.png"),
        Board("Chomp Chomp", "EyeBallB010.png"),
        Board("Cyberdemon", "DoomB01.png"),
        Board("Baron of Hell", "DoomB02.png"),
        Board("Natas", "DoomB03.png"),
        Board("CacoDemon", "DoomB04.png"),
        Board("Lost Soul", "DoomB05.png"),
        Board("Archvile", "DoomB06.png"),
        Board("Hell on Earth", "DoomB07.png"),
        Board("Deimos and Phobos", "DoomB08.png"),
        Board("Sergeant", "DoomB09.png"),
        Board("DOOM", "DoomB10.png"),
        Board("Red Baker Logo", "casB01.png"),
        Board("Birdhouse Logo", "casB02.png"),
        Board("Caballero Chinese Dragon", "casB03.png"),
        Board("City Stars Slam", "casB04.png"),
        Board("Element", "casB05.png"),
        Board("Enjoi Dingleberry Team", "casB06.png"),
        Board("Koston Olympic", "casB07.png"),
        Board("Shorty's Yellow Icon", "casB08.png"),
        Board("Toy Machine Red", "casB09.png"),
        Board("Zero New Firebird", "casB010.png"),
        Board("CS NH Deck", "CS_NH_board.png", is_extra=True),
        Board("Mystery Deck?", "cw_BS_unopened.png", is_extra=True),
        Board("THPS3", "GenericB01.png", is_extra=True),
        Board("Neversoft", "NeversoftB01.png", is_extra=True),
        Board("Test board", "Test_board.png", is_extra=True),
        Board("Test 2 board", "Test2_board.png", is_extra=True),
    ]
